#ifndef BRESSEIN_USER_INFO_H
#define BRESSEIN_USER_INFO_H
#include "user.h"
// all are stored as QByteArray except callId

namespace Bressein
{

    struct User::UserInfo
    {
        // from input
        QByteArray loginNumber;  // fetion number or mobile phone number
        QByteArray mobileNumber;
        QByteArray fetionNumber; // sId
        QByteArray password; //raw
        int callId; // initialized as 1
        QByteArray cnonce; // CN's value

        //from somewhere
        QByteArray personalVersion;
        QByteArray contactVersion;
        QByteArray customConfigVersion;

        // from Ssi
        QByteArray userId;       // user id
        QByteArray sipuri;       // sipuri like 'sip:100@fetion.com.cn'
        QByteArray ssic;         //cookie string
        QByteArray credential;

        QByteArray publicIp;     // public ip of current session
        QByteArray lastLoginIp;  // public ip of last login
        QByteArray lastLoginTime;// last login time , got after sipc authentication

        // from Sip-c reg
        QByteArray nonce;
        QByteArray key;
        QByteArray signature;

        // to validate
        QByteArray aeskey;     // random?
        QByteArray response;

        QByteArray pgGroupCallId_;    // callid for get group list request
        QByteArray groupInfoCallId;   // callid for get group info request
        // for local use
        QByteArray state; // presence state
        QByteArray loginStatus;       // login status code
        QByteArray nickname;
        QByteArray impression;    // mood phrase or impresa
        QByteArray portraitCrc;// a number generated by CRC algorithm
        QByteArray birthday;
        QByteArray country; //CN
        QByteArray province; //bj
        QByteArray city; //10 for beijing
        QByteArray gender; // 1 for male, 2 for female and 0 for private
        QByteArray boundToMobile;
        //TODO add more
        QByteArray smsOnLineStatus;
        int smsDayLimit;
        int smsDayCount;
        int smsMonthLimit;
        int smsMonthCount;
        int carrierStatus;
        quint64 loginTimes;
        int contactCount;
        int groupCount;
        QByteArray customConfig;//custom config string used to set personal information

        struct Verfication
        {
            QByteArray algorithm;
            QByteArray type;
            QByteArray text;
            QByteArray tips;
            QByteArray code;
            QByteArray guid;
        } *verfication; // initialized when needed

        struct SystemConfig
        {
            QByteArray serverVersion;
            QByteArray parametersVersion;
            QByteArray hintsVersion;
            QByteArray proxyIpPort;
            QByteArray serverNamePath; //get-uri
        } systemconfig;
    };
}
#endif
